/* CRIACAO DO BANCO */
CREATE DATABASE LES20131;

USE LES20131;

/* CRIACAO DAS TABELAS */
CREATE TABLE USUARIO (
        ID_USUARIO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
        EMAIL VARCHAR(100) NOT NULL UNIQUE,
        NOME VARCHAR(100) NOT NULL,
        SENHA CHAR(40) NOT NULL,
        EXCLUIDO INT(1) NOT NULL,
        BLOQUEADO INT(1) NOT NULL);
        
CREATE TABLE VIAJANTE (
		ID_USUARIO INT(5) NOT NULL PRIMARY KEY,
		SEXO CHAR(1) NOT NULL,
		DATA_NASCIMENTO DATE NOT NULL,
		IMAGEM BLOB,
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));
		
CREATE TABLE VIAGEM (
		ID_VIAGEM INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
		ID_USUARIO INT(5) NOT NULL,
		DESCRICAO VARCHAR(500) NOT NULL,
		EXCLUIDO INT(1) NOT NULL,
		BLOQUEADO INT(1) NOT NULL,
		FOREIGN KEY (ID_USUARIO) REFERENCES VIAJANTE(ID_USUARIO));
