/* CRIACAO DO BANCO */
CREATE DATABASE TRABALHOG1;

USE TRABALHOG1;

/* CRIACAO DAS TABELAS */
CREATE TABLE USUARIO (
        COD_USUARIO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
        USUARIO VARCHAR(50) NOT NULL,
        SENHA CHAR(32) NOT NULL);

CREATE TABLE LOCADOR (
        COD_LOCADOR INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CPF_LOCADOR VARCHAR(11) NOT NULL,
	NOME_LOCADOR VARCHAR(80) NOT NULL,
	DT_NASC DATE NOT NULL,
	ENDERECO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	FONE_LOCADOR INT(8) NOT NULL,
	NR_CNH VARCHAR(11) NOT NULL,
	ULT_ATUALIZACAO	DATE NOT NULL);

CREATE TABLE MARCA (
	COD_MARCA INT(5) AUTO_INCREMENT PRIMARY KEY,
	DESCR_MARCA VARCHAR(80),
	ULT_ATUALIZACAO	DATE NOT NULL);

CREATE TABLE MODELO (
	COD_MODELO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DESCR_MODELO VARCHAR(80),
	ULT_ATUALIZACAO	DATE NOT NULL,
	COD_MARCA INT(5) NOT NULL,
	FOREIGN KEY (COD_MARCA) REFERENCES MARCA(COD_MARCA));

CREATE TABLE VEICULO (
        COD_VEICULO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	PLACA VARCHAR(7) NOT NULL,
	ANO_FAB INT(4) NOT NULL,
	ANO_MODELO INT(4) NOT NULL,
	POTENCIA FLOAT(4) NOT NULL,
	KM_ATUAL INT(10) NOT NULL,
	CAPACIDADE INT(2) NOT NULL,
	COR VARCHAR(20),
	ULT_ATUALIZACAO	DATE NOT NULL,
	COD_MODELO INT(5) NOT NULL,
	FOREIGN KEY (COD_MODELO) REFERENCES MODELO(COD_MODELO));

CREATE TABLE LOCACAO (
        COD_LOCACAO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DTHR_LOCACAO DATETIME NOT NULL,
	DT_ENT_PREVISTA DATE NOT NULL,
	IND_SEGURO INT(1) NOT NULL,
	KM_INICIAL INT(10) NOT NULL,
	VLR_PREVISTO FLOAT(15) NOT NULL,
	ULT_ATUALIZACAO	DATE NOT NULL,
	DT_ENT DATE,
	KM_FINAL INT(10),
	VLR_PAGO FLOAT(15),
	COD_LOCADOR INT(5) NOT NULL,
	FOREIGN KEY (COD_LOCADOR) REFERENCES LOCADOR(COD_LOCADOR),
	COD_VEICULO INT(5) NOT NULL,
	FOREIGN KEY (COD_VEICULO) REFERENCES VEICULO(COD_VEICULO));


/* POPULANDO TABELAS */

INSERT INTO USUARIO(USUARIO, SENHA)VALUES("admin", MD5('admin'));

INSERT INTO MARCA(DESCR_MARCA,ULT_ATUALIZACAO)VALUES("FIAT",NOW());
INSERT INTO MARCA(DESCR_MARCA,ULT_ATUALIZACAO)VALUES("RENAULT",NOW());
INSERT INTO MARCA(DESCR_MARCA,ULT_ATUALIZACAO)VALUES("GM",NOW());

INSERT INTO MODELO
	(COD_MARCA,DESCR_MODELO,ULT_ATUALIZACAO)
	VALUES
	(2,"CLIO",NOW());
INSERT INTO MODELO
	(COD_MARCA,DESCR_MODELO,ULT_ATUALIZACAO)
	VALUES
	(1,"UNO",NOW());
INSERT INTO MODELO
	(COD_MARCA,DESCR_MODELO,ULT_ATUALIZACAO)
	VALUES
	(3,"CELTA",NOW());

INSERT INTO LOCADOR
	(COD_LOCADOR,CPF_LOCADOR,NOME_LOCADOR, DT_NASC, ENDERECO, CIDADE, CEP, FONE_LOCADOR, NR_CNH, ULT_ATUALIZACAO)
	VALUES
	(1, "99417049020","RAFAEL BERTO",STR_TO_DATE('12/31/1980', '%m/%d/%Y'),"RUA ABC, 154", "CANOAS", "92020001", "99999999", 123,NOW());
INSERT INTO LOCADOR
	(COD_LOCADOR,CPF_LOCADOR,NOME_LOCADOR, DT_NASC, ENDERECO, CIDADE, CEP, FONE_LOCADOR, NR_CNH, ULT_ATUALIZACAO)
	VALUES
	(2, "99417049010","JOSE ROBERTO",STR_TO_DATE('01/24/1978', '%m/%d/%Y'),"RUA CBA, 79", "PORTO ALEGRE", "92020001", "99999999", 123,NOW());

INSERT VEICULO
	(COD_VEICULO,PLACA,COD_MODELO,ANO_FAB,ANO_MODELO,POTENCIA,KM_ATUAL,CAPACIDADE,COR,ULT_ATUALIZACAO)
	VALUES
	(1, "ABC1212",3,2005,2005,1,15000,5,"VERMELHO",NOW());

INSERT VEICULO
	(COD_VEICULO,PLACA,COD_MODELO,ANO_FAB,ANO_MODELO,POTENCIA,KM_ATUAL,CAPACIDADE,COR,ULT_ATUALIZACAO)
	VALUES
	(2, "ABC1540",1,2011,2011,1,5000,5,"PRETO",NOW());

INSERT INTO LOCACAO
	(COD_LOCACAO,DTHR_LOCACAO,COD_LOCADOR,COD_VEICULO,DT_ENT_PREVISTA,IND_SEGURO,KM_INICIAL,VLR_PREVISTO,ULT_ATUALIZACAO,DT_ENT,KM_FINAL,VLR_PAGO)
	VALUES
	(1,NOW(),1,1,NOW(),1,10000,150.40,NOW(),STR_TO_DATE('04/16/2011', '%m/%d/%Y'),15000,180.70);

INSERT INTO LOCACAO
	(COD_LOCACAO,DTHR_LOCACAO,COD_LOCADOR,COD_VEICULO,DT_ENT_PREVISTA,IND_SEGURO,KM_INICIAL,VLR_PREVISTO,ULT_ATUALIZACAO)
	VALUES
	(2,NOW(),2,2,STR_TO_DATE('04/20/2011', '%m/%d/%Y'),1,5000,250.00,NOW());
