/* CRIACAO DO BANCO */
CREATE DATABASE LES20131;

USE LES20131;

/* CRIACAO DAS TABELAS */
CREATE TABLE USUARIO (
        ID_USUARIO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
        EMAIL VARCHAR(100) NOT NULL UNIQUE,
        NOME VARCHAR(100) NOT NULL,
        SENHA CHAR(40) NOT NULL,
        EXCLUIDO INT(1) NOT NULL,
        BLOQUEADO INT(1) NOT NULL);
        
CREATE TABLE VIAJANTE (
		ID_USUARIO INT(5) NOT NULL PRIMARY KEY,
		SEXO CHAR(1) NOT NULL,
		DATA_NASCIMENTO DATE NOT NULL,
		LATITUDE DOUBLE,
		LONGITUDE DOUBLE,
		IMAGEM BLOB,
		FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));
		
CREATE TABLE VIAGEM (
		ID_VIAGEM INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
		ID_USUARIO INT(5) NOT NULL,
		TITULO VARCHAR(50) NOT NULL,
		DESCRICAO VARCHAR(500) NOT NULL,
		DATA_INICIAL DATE,
		DATA_FINAL DATE,
		EXCLUIDO INT(1) NOT NULL,
		BLOQUEADO INT(1) NOT NULL,
		FOREIGN KEY (ID_USUARIO) REFERENCES VIAJANTE(ID_USUARIO));
		
CREATE TABLE IMAGEM_VIAGEM (
		ID_IMAGEM_VIAGEM INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
		ID_VIAGEM INT(5) NOT NULL,
		IMAGEM MEDIUMBLOB,
		FOREIGN KEY (ID_VIAGEM) REFERENCES VIAGEM(ID_VIAGEM));
		
CREATE TABLE CONTATO (
		ID_CONTATO INT(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
		ID_USUARIO1 INT(5) NOT NULL,
		ID_USUARIO2 INT(5) NOT NULL,
		DATA_INICIO DATE NOT NULL,
		UNIQUE KEY (ID_USUARIO1, ID_USUARIO2),
		FOREIGN KEY (ID_USUARIO1) REFERENCES VIAJANTE (ID_USUARIO),
		FOREIGN KEY (ID_USUARIO2) REFERENCES VIAJANTE (ID_USUARIO));
